### ISSUE TITLE
Carrier Duplication

### ISSUE THREAD

**Issue by Xjph** [fredjk-gh/ObservatoryPlugins#3]
Back in June of 2020 Frontier rolled out a patch that changed carrier IDs as a side effect. That means that carriers which span this change are reported as two carriers by Fleet Commander after a read all, one of which is _very_ stale.

Pretty minor, but if this could be handled gracefully it would be nice. :)

**Comment by fredjk-gh** [comment]
Ok, the fix is pretty basic as well: When adding a new carrier for a commander, if I find one for the commander already, I'll remove it and carry on. Basically, I assume there exists at most one carrier per commander.

It would be unreliable to assume the carrier name is the same, but for now, 1 carrier per commander is reasonable. As far as I know that decommissioning and re-buying a carrier doesn't change the callsign.

Fix will be committed soon and will in the next beta release of the plugin.
